apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secret-myapp
  namespace: myapp
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: demo-store
    kind: SecretStore
  target:
    name: my-super-secret
  dataFrom:
  - extract:
      key: kvv2/demo/myapp/config
