apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret
  namespace: myapp
spec:
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: demo/myapp/config
  deletionPolicy: Delete
  refreshInterval: 10s
  secretStoreRefs:
    - kind: SecretStore
      name: demo-store
  selector:
    secret:
      name: my-super-secret-credentials
  updatePolicy: Replace
