apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
spec:
  vaultAuthRef: vault/myvaultauth
  mount: kvv2
  type: kv-v2
  path: demo/config
  refreshAfter: 10s
  destination:
    create: true
    name: my-super-secret
  rolloutRestartTargets:
  - kind: Deployment
    name: myapp
